"""empty message

Revision ID: 159dcd079b9d
Revises: 
Create Date: 2023-04-01 16:19:07.071445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159dcd079b9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('categoryid', sa.Integer(), nullable=False),
    sa.Column('categoryname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('categoryid')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('bed', sa.Integer(), nullable=False),
    sa.Column('bath', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.categoryid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    op.drop_table('categories')
    # ### end Alembic commands ###
